Rails:
  Enabled: true

Metrics/LineLength:
  Max: 170

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

#AllCops:
#  TargetRubyVersion: 2.3.1

